export const USER_ACTION_TYPES = {
    CHECK_USER_SESSION : 'USER/CHECKUSERSESSION',
    GOOGLE_SIGN_IN_START : 'USER/GOOGLESIGNINSTART',
    EMAIL_SIGNIN_START : 'USER/EMAIL_SIGNIN_START',
    SIGNIN_SUCCESS : 'USER/SIGNINSUCCESS',
    SIGNIN_FAILED : 'USER/SIGNINFAILED',
    EMAIL_SIGNUP_START : 'USER/EMAIL_SIGNUP_START',
    SIGNUP_SUCCESS:"USER/SIGNUPSUCCESS",
    SIGNUP_FAILED:'USER/SIGNUPFAILED',
    SIGNOUT_START : 'USER/SIGNOUTSTART',
    SIGNOUT_SUCCESS:"USER/SIGNOUTSUCCESS",
    SIGNOUT_FAILED:'USER/SIGNOUTFAILED'
  };